env:
    global:
        - PACKAGE="EasyClangComplete"
        - SUBLIME_TEXT_VERSION="3"

sudo: false
language: python
python: "3.6"

matrix:
    include:
    - os: linux
      dist: xenial
      sudo: required
      services:
      - xvfb
    - os: osx
      language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            pip install --upgrade pip pycodestyle pep257;
            pip install --upgrade coverage==4.5.4;
            pip install --upgrade mkdocs mkdocs-material;
            sudo apt-get update -yqq;
            sudo apt-get install -y clang;
            curl -L -o bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64";
            chmod +x bazelisk && sudo mv bazelisk /usr/local/bin/bazel;
      fi

install:
    - sh travis.sh bootstrap
    - sh travis.sh install_package_control

script:
    - ls
    - sh travis.sh run_tests --coverage
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            coverage xml -o cobertura.xml;
            mkdocs build --verbose --clean --strict;
      fi

after_success:
    - bash <(curl -Ls https://coverage.codacy.com/get.sh)

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux

notifications:
    email: false
