# -*- coding: utf-8 -*-
"""retracer-automation-script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hyaq9XSo7zpikBmTrxtSjDu-9VxXeAPP
"""

# may not be required
# !apt install g++
# !apt install libc6
# !g++ sol.cpp -o sol
# !chmod +x ./sol
# !./sol

import subprocess

# Define the command to run
cmd = './sol'

for i in range(1, 101):
    # Start the process with the current number as input
    process = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    process.stdin.write(str(i).encode('utf-8') + b'\n')

    # Get the output from the process
    output = process.communicate()[0]

    # Print the output
    print(f"Input: {i} : Output: {output.decode('utf-8')}", end = '')
